### ISSUE TITLE
Support usage with ng-model.

### ISSUE THREAD

**Issue by ravshansbox** [nverba/pikaday-angular#19]
Support usage with ng-model. Example: 
<input type="text" pikaday ng-model="value">
Some IDEs better support ng-model.

**Comment by Narretz** [comment]
I agree. Inputs in Angular are supposed to work with ngModel, and pikaday should not be an exception. A developer could also use the ngModel rendering / parsing pipelines additionally to anything pikaday does.

**Comment by tanyagray** [comment]
In case anyone needs it, have created a fork which supports ng-model here:
https://github.com/tanyagray/pikaday-angular

Haven't created a PR as I haven't done docs or tests, and I suspect the code could be tidier, but have been using it and it works for my case. 

Have been using a UTC date string as the model.
