### ISSUE TITLE
Unable to use custom format to be displayed with pikaday

### ISSUE THREAD

**Issue by mastermind1981** [nverba/pikaday-angular#9]
Hi,

First of all, Thank you for your great work.

I have a problem setting a date (string) on a pikaday directive : in fact, i think the problem is a problem a format config. I tried to set in the config but it seems it doesn't work.

My format is 'DD/MM/YYYY'  when i use these attributes : default-date="17/01/2007"  set-default-date="true" it doesn't work, but when i use default-date="12/01/2007" it shows the correct value but with the wrong format "Sat Dec 01 2007" .

Here is a plunker exposing the problem http://plnkr.co/edit/AVePt7?p=preview .

Thanks in advance.

**Comment by nverba** [comment]
Thanks @mastermind1981, I'm glad you find this useful.

The format option only affects the input field (text input & output), and the `.toString` method of the Pikaday object, basically the parts the end user interacts with. Coercing a date object from the `default-date` is done by a simple `new Date('string')` behind the scenes, so the format of this string needs to be one the JavaScript [Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date) method can understand. See [Date.parse()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse) for accepted formats and some of the issues with non standard strings and inconsistency with browsers.

So regarding the `default-date` attribute, we are somewhat restricted here to string inputs such as `YYYY-MM-DD` for the sake of stability.

I tend to keep all my date strings in the `ISO 8601` compliant format in the application, and use moment.js or Angular's built in Date formatters when displaying the date to the user, as depending on the locale, date strings can be ambiguous. 

i.e. `01/06/2012` = __UK 1st June 2012__ & __US 6th Jan 2012__.

Hope this helps.

**Comment by mastermind1981** [comment]
Thank you for your answer.

Actually, i am using moment so i decided to modify the code of angular-pikaday to use 'DD/MM/YYYY' format, like this:
```
            case "minDate":
            case "maxDate":
            case "defaultDate":

              config[attr] = moment(value, config["format"]).toDate();
              break;
```

and it works fine.

**Comment by nverba** [comment]
That's a good solution.

I can't make my mind up whether I should adopt this approach, or not.
